DROP TABLE USERS;
DROP TABLE ORDERS;
CREATE TABLE USERS (Id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), Name VARCHAR(256), Age INTEGER, PRIMARY KEY (Id));
CREATE TABLE ORDERS (Id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), Name VARCHAR(45), CustomerId INTEGER, SalesPersonalId INTEGER, PRIMARY KEY (Id));